
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Levak
 */
public class ConditionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConditionFrame
     */
    public ConditionFrame() {
        initComponents();
        ImageIcon icn = new ImageIcon(getClass().getResource("nremote.png"));
        this.setIconImage(icn.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SUP = new javax.swing.JButton();
        INF = new javax.swing.JButton();
        DIFF = new javax.swing.JButton();
        SUPE = new javax.swing.JButton();
        INFE = new javax.swing.JButton();
        SUCHTHAT = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        SUP.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        SUP.setText(">");
        SUP.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPActionPerformed(evt);
            }
        });
        jPanel1.add(SUP);

        INF.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        INF.setText("<");
        INF.setMargin(new java.awt.Insets(2, 0, 2, 0));
        INF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFActionPerformed(evt);
            }
        });
        jPanel1.add(INF);

        DIFF.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        DIFF.setText("≠");
        DIFF.setMargin(new java.awt.Insets(2, 0, 2, 0));
        DIFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIFFActionPerformed(evt);
            }
        });
        jPanel1.add(DIFF);

        SUPE.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        SUPE.setText("≥");
        SUPE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SUPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPEActionPerformed(evt);
            }
        });
        jPanel1.add(SUPE);

        INFE.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        INFE.setText("≤");
        INFE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        INFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFEActionPerformed(evt);
            }
        });
        jPanel1.add(INFE);

        SUCHTHAT.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        SUCHTHAT.setText("|");
        SUCHTHAT.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SUCHTHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUCHTHATActionPerformed(evt);
            }
        });
        jPanel1.add(SUCHTHAT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPActionPerformed
        sendEvent(">");
    }//GEN-LAST:event_SUPActionPerformed

    private void INFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFActionPerformed
        sendEvent("<");
    }//GEN-LAST:event_INFActionPerformed

    private void DIFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIFFActionPerformed
        sendEvent("~ctrl_=~");
    }//GEN-LAST:event_DIFFActionPerformed

    private void SUPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPEActionPerformed
        sendEvent("~ctrl_>~");
    }//GEN-LAST:event_SUPEActionPerformed

    private void INFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFEActionPerformed
        sendEvent("~ctrl_<~");
    }//GEN-LAST:event_INFEActionPerformed

    private void SUCHTHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUCHTHATActionPerformed
        sendEvent("~suchthat~");
    }//GEN-LAST:event_SUCHTHATActionPerformed

    private void sendEvent(String keyStr) {
        try {
            Remote.sendEvent(keyStr);
        } catch (Exception e) { }
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConditionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConditionFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIFF;
    private javax.swing.JButton INF;
    private javax.swing.JButton INFE;
    private javax.swing.JButton SUCHTHAT;
    private javax.swing.JButton SUP;
    private javax.swing.JButton SUPE;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
