import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Levak
 */
public class PiFrame extends javax.swing.JFrame {

    /**
     * Creates new form PiFrame
     */
    public PiFrame() {
        initComponents();
        ImageIcon icn = new ImageIcon(getClass().getResource("nremote.png"));
        this.setIconImage(icn.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PI = new javax.swing.JButton();
        IMAGINARY = new javax.swing.JButton();
        INFINITY = new javax.swing.JButton();
        THETA = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        PI.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        PI.setText("π");
        PI.setMargin(new java.awt.Insets(2, 0, 2, 0));
        PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIActionPerformed(evt);
            }
        });
        jPanel1.add(PI);

        IMAGINARY.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        IMAGINARY.setText("");
        IMAGINARY.setMargin(new java.awt.Insets(2, 0, 2, 0));
        IMAGINARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMAGINARYActionPerformed(evt);
            }
        });
        jPanel1.add(IMAGINARY);

        INFINITY.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        INFINITY.setText("∞");
        INFINITY.setMargin(new java.awt.Insets(2, 0, 2, 0));
        INFINITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFINITYActionPerformed(evt);
            }
        });
        jPanel1.add(INFINITY);

        THETA.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        THETA.setText("θ");
        THETA.setMargin(new java.awt.Insets(2, 0, 2, 0));
        THETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THETAActionPerformed(evt);
            }
        });
        jPanel1.add(THETA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIActionPerformed
        sendEvent("~pi~");
    }//GEN-LAST:event_PIActionPerformed

    private void IMAGINARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMAGINARYActionPerformed
        sendEvent("~imaginary~");
    }//GEN-LAST:event_IMAGINARYActionPerformed

    private void INFINITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFINITYActionPerformed
        sendEvent("~ctrl_imaginary~");
    }//GEN-LAST:event_INFINITYActionPerformed

    private void THETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THETAActionPerformed
        sendEvent("~theta~");
    }//GEN-LAST:event_THETAActionPerformed

    private void sendEvent(String keyStr) {
        try {
            Remote.sendEvent(keyStr);
        } catch (Exception e) {
        }
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IMAGINARY;
    private javax.swing.JButton INFINITY;
    private javax.swing.JButton PI;
    private javax.swing.JButton THETA;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
