
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Levak
 */
public class SymbolsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SymbolsFrame
     */
    public SymbolsFrame() {
        initComponents();
        ImageIcon icn = new ImageIcon(getClass().getResource("nremote.png"));
        this.setIconImage(icn.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        QMARK = new javax.swing.JButton();
        EMARK = new javax.swing.JButton();
        DOLLAR = new javax.swing.JButton();
        DEGREE = new javax.swing.JButton();
        MINUTE = new javax.swing.JButton();
        SECOND = new javax.swing.JButton();
        COLON = new javax.swing.JButton();
        SEMICOLON = new javax.swing.JButton();
        UNDERSCORE = new javax.swing.JButton();
        BACKSLASH = new javax.swing.JButton();
        PERCENT = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 5));

        QMARK.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        QMARK.setText("?");
        QMARK.setMargin(new java.awt.Insets(2, 0, 2, 0));
        QMARK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QMARKActionPerformed(evt);
            }
        });
        jPanel1.add(QMARK);

        EMARK.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        EMARK.setText("!");
        EMARK.setMargin(new java.awt.Insets(2, 0, 2, 0));
        EMARK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMARKActionPerformed(evt);
            }
        });
        jPanel1.add(EMARK);

        DOLLAR.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        DOLLAR.setText("$");
        DOLLAR.setMargin(new java.awt.Insets(2, 0, 2, 0));
        DOLLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOLLARActionPerformed(evt);
            }
        });
        jPanel1.add(DOLLAR);

        DEGREE.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        DEGREE.setText("°");
        DEGREE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        DEGREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEGREEActionPerformed(evt);
            }
        });
        jPanel1.add(DEGREE);

        MINUTE.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        MINUTE.setText("'");
        MINUTE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        MINUTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINUTEActionPerformed(evt);
            }
        });
        jPanel1.add(MINUTE);

        SECOND.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        SECOND.setText("\"");
        SECOND.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SECOND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SECONDActionPerformed(evt);
            }
        });
        jPanel1.add(SECOND);

        COLON.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        COLON.setText(":");
        COLON.setMargin(new java.awt.Insets(2, 0, 2, 0));
        COLON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLONActionPerformed(evt);
            }
        });
        jPanel1.add(COLON);

        SEMICOLON.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        SEMICOLON.setText(";");
        SEMICOLON.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SEMICOLON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMICOLONActionPerformed(evt);
            }
        });
        jPanel1.add(SEMICOLON);

        UNDERSCORE.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        UNDERSCORE.setText("_");
        UNDERSCORE.setMargin(new java.awt.Insets(2, 0, 2, 0));
        UNDERSCORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNDERSCOREActionPerformed(evt);
            }
        });
        jPanel1.add(UNDERSCORE);

        BACKSLASH.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
        BACKSLASH.setText("\\");
            BACKSLASH.setMargin(new java.awt.Insets(2, 0, 2, 0));
            BACKSLASH.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BACKSLASHActionPerformed(evt);
                }
            });
            jPanel1.add(BACKSLASH);

            PERCENT.setFont(new java.awt.Font("TI-Nspire Sans", 0, 12)); // NOI18N
            PERCENT.setText("%");
            PERCENT.setMargin(new java.awt.Insets(2, 0, 2, 0));
            PERCENT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    PERCENTActionPerformed(evt);
                }
            });
            jPanel1.add(PERCENT);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void QMARKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QMARKActionPerformed
        sendEvent("?");
    }//GEN-LAST:event_QMARKActionPerformed

    private void EMARKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMARKActionPerformed
        sendEvent("~ctrl_suchthat~");
    }//GEN-LAST:event_EMARKActionPerformed

    private void DOLLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOLLARActionPerformed
        sendEvent("~ctrl_quote~");
    }//GEN-LAST:event_DOLLARActionPerformed

    private void DEGREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEGREEActionPerformed
        sendEvent("~ctrl_'~");
    }//GEN-LAST:event_DEGREEActionPerformed

    private void MINUTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINUTEActionPerformed
        sendEvent("'");
    }//GEN-LAST:event_MINUTEActionPerformed

    private void SECONDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SECONDActionPerformed
        sendEvent("\"");
    }//GEN-LAST:event_SECONDActionPerformed

    private void COLONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLONActionPerformed
        sendEvent(":");
    }//GEN-LAST:event_COLONActionPerformed

    private void SEMICOLONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMICOLONActionPerformed
        sendEvent("~ctrl_:~");
    }//GEN-LAST:event_SEMICOLONActionPerformed

    private void UNDERSCOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNDERSCOREActionPerformed
        sendEvent("~ctrl_space~");
    }//GEN-LAST:event_UNDERSCOREActionPerformed

    private void BACKSLASHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKSLASHActionPerformed
        sendEvent("~shift_slash~");
    }//GEN-LAST:event_BACKSLASHActionPerformed

    private void PERCENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERCENTActionPerformed
        sendEvent("%");
    }//GEN-LAST:event_PERCENTActionPerformed

    private void sendEvent(String keyStr) {
        try {
            Remote.sendEvent(keyStr);
        } catch (Exception e) { }
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SymbolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SymbolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SymbolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SymbolsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SymbolsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKSLASH;
    private javax.swing.JButton COLON;
    private javax.swing.JButton DEGREE;
    private javax.swing.JButton DOLLAR;
    private javax.swing.JButton EMARK;
    private javax.swing.JButton MINUTE;
    private javax.swing.JButton PERCENT;
    private javax.swing.JButton QMARK;
    private javax.swing.JButton SECOND;
    private javax.swing.JButton SEMICOLON;
    private javax.swing.JButton UNDERSCORE;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
