
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Levak
 */
public class TrigFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrigFrame
     */
    public TrigFrame() {
        initComponents();
        ImageIcon icn = new ImageIcon(getClass().getResource("nremote.png"));
        this.setIconImage(icn.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SIN = new javax.swing.JButton();
        COS = new javax.swing.JButton();
        TAN = new javax.swing.JButton();
        ASIN = new javax.swing.JButton();
        ACOS = new javax.swing.JButton();
        ATAN = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        SIN.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        SIN.setText("sin");
        SIN.setMargin(new java.awt.Insets(2, 0, 2, 0));
        SIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SINActionPerformed(evt);
            }
        });
        jPanel1.add(SIN);

        COS.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        COS.setText("cos");
        COS.setMargin(new java.awt.Insets(2, 0, 2, 0));
        COS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COSActionPerformed(evt);
            }
        });
        jPanel1.add(COS);

        TAN.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        TAN.setText("tan");
        TAN.setMargin(new java.awt.Insets(2, 0, 2, 0));
        TAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TANActionPerformed(evt);
            }
        });
        jPanel1.add(TAN);

        ASIN.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        ASIN.setText("sin");
        ASIN.setMargin(new java.awt.Insets(2, 0, 2, 0));
        ASIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASINActionPerformed(evt);
            }
        });
        jPanel1.add(ASIN);

        ACOS.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        ACOS.setText("cos");
        ACOS.setToolTipText("");
        ACOS.setMargin(new java.awt.Insets(2, 0, 2, 0));
        ACOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACOSActionPerformed(evt);
            }
        });
        jPanel1.add(ACOS);

        ATAN.setFont(new java.awt.Font("TI-Nspire Sans", 0, 11)); // NOI18N
        ATAN.setText("tan");
        ATAN.setMargin(new java.awt.Insets(2, 0, 2, 0));
        ATAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATANActionPerformed(evt);
            }
        });
        jPanel1.add(ATAN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COSActionPerformed
        sendEvent("~cos~");
    }//GEN-LAST:event_COSActionPerformed

    private void SINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SINActionPerformed
        sendEvent("~sin~");
    }//GEN-LAST:event_SINActionPerformed

    private void TANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TANActionPerformed
        sendEvent("~tan~");
    }//GEN-LAST:event_TANActionPerformed

    private void ACOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACOSActionPerformed
        sendEvent("~ctrl_cos~");
    }//GEN-LAST:event_ACOSActionPerformed

    private void ASINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASINActionPerformed
        sendEvent("~ctrl_sin~");
    }//GEN-LAST:event_ASINActionPerformed

    private void ATANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATANActionPerformed
        sendEvent("~ctrl_tan~");
    }//GEN-LAST:event_ATANActionPerformed

    private void sendEvent(String keyStr) {
        try {
            Remote.sendEvent(keyStr);
        } catch (Exception e) { }
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrigFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACOS;
    private javax.swing.JButton ASIN;
    private javax.swing.JButton ATAN;
    private javax.swing.JButton COS;
    private javax.swing.JButton SIN;
    private javax.swing.JButton TAN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
